### ISSUE TITLE
LAMA model

### ISSUE THREAD

**Issue by elenashi912** [yael-vinker/SceneSketch#11]
Hi!
Really appreciate this awesome work!
I am trying to set up the environment and want to download the LAMA model following the instruction. However, looks like the model is no longer available via the URL. Getting this error below:
```
Traceback (most recent call last):
  File "/home/elena/.local/bin/yadisk-direct", line 8, in <module>
    sys.exit(main())
  File "/home/elena/.local/lib/python3.10/site-packages/wldhx/yadisk_direct/main.py", line 23, in main
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/home/elena/.local/lib/python3.10/site-packages/wldhx/yadisk_direct/main.py", line 23, in <listcomp>
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/home/elena/.local/lib/python3.10/site-packages/wldhx/yadisk_direct/main.py", line 12, in get_real_direct_link
    return pk_request.json()['href']
KeyError: 'href'
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```
Would the author like to clarify this and provide a new LAMA model?

**Comment by ayanban011** [comment]
You can download the lama model from this. https://huggingface.co/smartywu/big-lama/blob/main/big-lama.zip. Just update the curl link.
