### ISSUE TITLE
lama model is not available

### ISSUE THREAD

**Issue by Jl-wei** [yael-vinker/SceneSketch#7]
When I run `curl -L $(yadisk-direct https://disk.yandex.ru/d/ouP6l8VJ0HpMZg) -o big-lama.zip`, I got the following error message:

```
Traceback (most recent call last):
  File "/home/miniconda/envs/habitat/bin/yadisk-direct", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda/envs/habitat/lib/python3.7/site-packages/wldhx/yadisk_direct/main.py", line 23, in main
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/home/miniconda/envs/habitat/lib/python3.7/site-packages/wldhx/yadisk_direct/main.py", line 23, in <listcomp>
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/home/miniconda/envs/habitat/lib/python3.7/site-packages/wldhx/yadisk_direct/main.py", line 12, in get_real_direct_link
    return pk_request.json()['href']
KeyError: 'href'
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by Jl-wei** [comment]
Seems that the model from [link](https://github.com/advimman/lama) can be an alternative
```
curl -LJO https://huggingface.co/smartywu/big-lama/resolve/main/big-lama.zip
unzip big-lama.zip
```
